### PR TITLE
Use biome as a linter, formatter

### PR DESCRIPTION
**Pull request by bjgavilanes**
biome is a prettier and eslint alternative written in Rust. The main reason I'm using biome is because it's, at least, 15x faster than mentioned alternatives.

I used `biome check --write` in the root directory. Biome should be installed in the host machine using cargo, or the system's package manager. If the needs arises, I can describe a Cargo.toml that does setup it up.

A good follow up PR would be to implement a task runner; whether `make`, `just`, or another alternative.

### CODE REVIEW

**Comment by davcortez** [comment]
Hi,  @bjgavilanes , please add instructions in README.md that could help to contributors.

**Comment by bjgavilanes** [comment]
Hello!,

On Wed Dec 4, 2024 at 2:23 PM -03, David wrote:
> Hi,  @bjgavilanes , please add instructions in README.md that could help to contributors.


Yes, would like to. But first, we got to define if we use nix as a package and dependency management; or we just add biome at package.json -- and let pnpm work as usual.

As documentent in a issue, I argue for nix case; but I'm waiting discussion over there.

**Comment by bjgavilanes** [comment]
Greetings,

Doing a simple testing using hyperfine,

`hyperfine -w 1 -r 1 "pnpx @biomejs/biome check || echo "k" " "biome check || echo "k" "`

I got this result:

``` sh
Benchmark 1: pnpx @biomejs/biome check || echo k 
  Time (abs ≡):        851.2 ms               [User: 784.6 ms, System: 180.5 ms]
 
Benchmark 2: biome check || echo k 
  Time (abs ≡):         44.9 ms               [User: 50.0 ms, System: 14.3 ms]
 
Summary
  biome check || echo k  ran
   18.94 times faster than pnpx @biomejs/biome check || echo k 
```

So I'll implement nix as a package and dependency manager.

**Comment by bjgavilanes** [comment]
For the heads up, I'm implementing this in a experimental branch. I haven't push anything yet -- too mucho work :'( --; but it'll get it done this week.

I that experimental branch, I'm using a shell.nix to declare global and project dependencies requiered for this repo -- such as pnpm and biome, for example. --

**Comment by bjgavilanes** [comment]
Closing because I'm going to write a PR dedicated to biome + dprint setup.

**Pull request closed without merging**
